# Generated by Django 5.1.4 on 2025-01-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isSet',
            field=models.BooleanField(default=False),
        ),
    ]
