# Generated by Django 5.1.4 on 2025-01-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isNew',
            field=models.BooleanField(),
        ),
    ]
