# Generated by Django 5.1.4 on 2025-01-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='is_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='other',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='other',
            name='is_notebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='other',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
